### ISSUE TITLE
PG 2015 rollout checklist

### ISSUE THREAD

**Issue by ghost** [unikent/programmes-plant#748]
- [x] Deploy code (of-course + Programmes Plant)
- [x] Run PP migrations
- [x] Update fees config on www-live
- [x] Change the front-end PG year in system settings
- [x] Edit DB to remove overrideable PG how_to_apply from main/revision of programme settings
- [x] Run SitsImport script
- [x] Run Fees import script
- [x] Turn off "clearing mode" for of-course
- [x] Update site configurtion (2014->2015 in banner)
- [x] Clear cache files
- [x] Deploy pantheon changes (similar to of-course)
- [x] Add (or check existence of) SitsImport Cron
- [x] Add Fees import CRON (Make this regular? 5/10 minutes? )

ALSO:

Double check fees import is checking old file correctly to avoid importing fees when no changes have happened.
